channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.2.1
- pip:
  - mlflow==2.11.3
  - attrs==22.1.0
  - cffi==1.15.1
  - cloudpickle==2.2.1
  - colorama==0.4.6
  - defusedxml==0.7.1
  - dill==0.3.6
  - huggingface-hub==0.30.2
  - ipython==8.15.0
  - jaraco-classes==3.2.1
  - jaraco-collections==5.1.0
  - jaraco-context==5.3.0
  - jaraco-functools==4.0.1
  - jaraco-text==3.12.1
  - lz4==4.3.2
  - matplotlib==3.7.2
  - more-itertools==8.12.0
  - numpy==1.23.5
  - packaging==24.2
  - pandas==2.0.3
  - pathlib==1.0.1
  - protobuf==4.25.3
  - psutil==5.9.0
  - pyyaml==6.0.2
  - requests==2.32.3
  - scikeras==0.13.0
  - scikit-learn==1.4.2
  - scipy==1.15.2
  - tblib==1.7.0
  - tensorflow==2.16.2
name: mlflow-env
