artifact_location: file:///Users/javimartinfuentes/Documents/GitHub/despegues/src/models/mlflow_experiments/0
creation_time: 1745671813007
experiment_id: '0'
last_update_time: 1745671813007
lifecycle_stage: active
name: Default
