artifact_uri: /Users/maria/Dropbox/UCM/PD2/despegues/src/models/mlflow_maria/492837484277213997/685b4c3581cf4e56acd297d33ccbffad/artifacts
end_time: 1745696959632
entry_point_name: ''
experiment_id: '492837484277213997'
lifecycle_stage: active
run_id: 685b4c3581cf4e56acd297d33ccbffad
run_name: marvelous-fox-139
run_uuid: 685b4c3581cf4e56acd297d33ccbffad
source_name: ''
source_type: 4
source_version: ''
start_time: 1745696954309
status: 3
tags: []
user_id: maria
