artifact_location: file:///Users/javimartinfuentes/Documents/GitHub/despegues/src/models/mlflow_experiments/654205553581685568
creation_time: 1745671878839
experiment_id: '654205553581685568'
last_update_time: 1745671878839
lifecycle_stage: active
name: takeoff_time_prediction
