artifact_uri: file:///Users/javimartinfuentes/Documents/GitHub/despegues/src/models/mlflow_experiments/654205553581685568/dc0eb4ec01ab4c2898a755f676bac0dd/artifacts
end_time: 1745695708182
entry_point_name: ''
experiment_id: '654205553581685568'
lifecycle_stage: active
run_id: dc0eb4ec01ab4c2898a755f676bac0dd
run_name: vaunted-crow-734
run_uuid: dc0eb4ec01ab4c2898a755f676bac0dd
source_name: ''
source_type: 4
source_version: ''
start_time: 1745695708138
status: 4
tags: []
user_id: maria
