artifact_uri: /Users/maria/Dropbox/UCM/PD2/despegues/src/models/mlflow_maria/492837484277213997/ddb1137d5bb342dd84ab73f7cfbf6e38/artifacts
end_time: 1745782352036
entry_point_name: ''
experiment_id: '492837484277213997'
lifecycle_stage: active
run_id: ddb1137d5bb342dd84ab73f7cfbf6e38
run_name: smiling-hound-378
run_uuid: ddb1137d5bb342dd84ab73f7cfbf6e38
source_name: ''
source_type: 4
source_version: ''
start_time: 1745782345883
status: 3
tags: []
user_id: maria
